# Merge
# https://github.com/zacanger/profane-words
# and
# https://github.com/thisandagain/washyourmouthoutwithsoap/blob/develop/data/build.json
# and
# https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words


english_flagged_words = [
    "anal",
    "bareback",
    "bbw",
    "bdsm",
    "blowjob",
    "blowjobs",
    "brazzers",
    "bukkake",
    "camgirl",
    "camwhore",
    "cocksucking",
    "cougar",
    "creampie",
    "cuckold",
    "cum",
    "cumming",
    "cums",
    "cumshot",
    "cumshots",
    "cumslut",
    "cunnilingus",
    "deepthroat",
    "deepthroating",
    "dildo",
    "dildos",
    "dogging",
    "doggystyle",
    "dominatrix",
    "erotic",
    "fellatio",
    "femdom",
    "fingering",
    "fisting",
    "footjob",
    "gangbang",
    "handjob",
    "hentai",
    "horney",
    "horniest",
    "horny",
    "jism",
    "jizz",
    "masterbating",
    "masturbate",
    "masturbating",
    "masturbation",
    "milf",
    "orgies",
    "orgy",
    "pegging",
    "porn",
    "pornhub",
    "porno",
    "pornos",
    "pornstar",
    "pornstars",
    "redtube",
    "rimming",
    "slutty",
    "squirting",
    "strapon",
    "threesome",
    "vibrator",
    "xhamster",
    "xnxx",
    "xvideos",
    "xxx",
    "youporn",
]


flagged_words = {
    "ar": english_flagged_words
    + [
        "إباحي",
        "احتلام",
        "است",
        "استمناء",
        "اغتصاب",
        "أورغازم",
        "إيروتيك",
        "أير",
        "بز",
        "بزاز",
        "بظر",
        "بورن",
        "بيضان",
        "مص",
        "ثدي",
        "جماع",
        "جنس",
        "حلمة",
        "خلاعة",
        "خنثي",
        "خول",
        "دعارة",
        "زب",
        "سحاق",
        "سحاقية",
        "سكس",
        "سيكس",
        "شاذ",
        "شبق",
        "شرج",
        "شرموطة",
        "شهواني",
        "شهوة",
        "طيز",
        "عادة السرية",
        "عاهرة",
        "عرص",
        "فاسقة",
        "فرج",
        "قحبة",
        "قضيب",
        "كس",
        "لحس",
        "لعق",
        "لواط",
        "لوطي",
        "مؤخرة",
        "متناك",
        "متناكة",
        "مومس",
        "مثير",
        "مص",
        "مضاجعة",
        "مفلقسة",
        "مني",
        "مهتاج",
        "نشوة",
        "نكاح",
        "نيك",
    ],
    "ca": english_flagged_words
    + [
        "anal",
        "anals",
        "anus",
        "cul",
        "culs",
        "bollera",
        "bolleres",
        "puta",
        "putes",
        "femelles",
        "mamada",
        "mamadera",
        "mamaderes",
        "mamades",
        "teta",
        "tetes",
        "clitoris",
        "polla",
        "polles",
        "pollera",
        "polleres",
        "merda",
        "escorreguda",
        "escorregudes",
        "correguda",
        "corregudes",
        "cunillingus",
        "consolador",
        "consoladors",
        "canalla",
        "ejaculació",
        "ejaculacions",
        "ejaculat",
        "ejaculats",
        "ejacula",
        "ejacular",
        "ejaculant",
        "ejacules",
        "fel.lació",
        "follar",
        "follat",
        "follats",
        "folla",
        "follant",
        "folles",
        "marchaatrás",
        "marcha atrás",
        "masoquista",
        "masturbar-se",
        "masturbar",
        "masturbat",
        "masturbats",
        "masturba",
        "masturbant",
        "masturbes",
        "masturbació",
        "masturbacions",
        "puta mare",
        "nazi",
        "negre",
        "negra",
        "negres",
        "orgasme",
        "orgasmes",
        "penis",
        "caca",
        "porno",
        "pornografia",
        "pubis",
        "violació",
        "violacions",
        "violador",
        "violadors",
        "erecte",
        "erectes",
        "empinat",
        "empinats",
        "empinada",
        "empinades"
        "escrot",
        "escrots",
        "semen",
        "semens",
        "sexe",
        "sexes",
        "borratxo",
        "borratxos",
        "transsexual",
        "transsexuals",
        "esmegma",
        "fill de puta",
        "fills de puta",
        "filla de puta",
        "filles de puta",
        "testicle",
        "testicles",
        "cagarro",
        "cagarros",
        "vagina",
        "vagines",
        "cony",
        "conys",
        "viagra",
        "viagra",
        "viagres",
        "palla",
        "palles",
        "xxx",
        "bastarda",
        "bastardes",
        "bastard",
        "bastards",
        "cabrona",
        "cabrones",
        "cabrons",
        "cabró",
        "marica",
        "mariques",
        "maricon",
        "mariconazo",
        "mariconazos",
        "maricons",
        "maricó",
        "maricón",
        "chupapollas",
        "xupapolles",
        "cipote",
        "cipotes",
        "cochina",
        "cochinas",
        "concha",
        "conches",
        "coneja",
        "conejas",
        "conilla",
        "conilles",
        "escalfabraguetes",
        "escalfapolles",
        "infern",
        "inferns",
        "soplapollas",
        "soplapolles",
        "tortillera",
        "tortilleres",
        "verga",
        "vergues",
        "zorra",
        "zorres"
        "ramera",
        "rameres",
        "meuca",
        "meuques",
        "bagassa",
        "bagasses",
        "escorreguda",
        "escorregudes",
        "corre's",
        "corre't",
        "escórre's",
        "escórre't",
        "córrer-se",
        "escórrer-se",
        "corregut",
        "escorregut",
        "mamella",
        "mamelles",
        "xupa",
        "chupa",
        "chuma",
        "trans",
        "colló",
        "collons",
        "guarra",
        "guarres",
        "porca",
        "porques",
        "marrana",
        "marranes",
        "ties",
        "tia",
        "nena",
        "nenes",
        "negra",
        "calentorra",
        "calentorres",
        "trans",
        "trio",
        "coit"
    ],
    "en": english_flagged_words,
    "es": english_flagged_words
    + [
        "Asesinato",
        "Bollera",
        "Cabrón",
        "Caca",
        "Chupada",
        "Chupapollas",
        "Chupetón",
        "Concha de tu madre",
        "Coprofagía",
        "Coño",
        "Culo",
        "Drogas",
        "Esperma",
        "Fiesta de salchichas",
        "Follador",
        "Follar",
        "Gilipichis",
        "Gilipollas",
        "Hacer una paja",
        "Haciendo el amor",
        "Heroína",
        "Hija de puta",
        "Hijaputa",
        "Hijo de puta",
        "Hijoputa",
        "Idiota",
        "Imbécil",
        "Jilipollas",
        "Kapullo",
        "Lameculos",
        "Maciza",
        "Macizorra",
        "Mamada",
        "Marica",
        "Mariconazo",
        "Maricón",
        "Mierda",
        "Nazi",
        "Orina",
        "Pedo",
        "Pendejo",
        "Pervertido",
        "Pezón",
        "Pinche",
        "Pis",
        "Prostituta",
        "Puta",
        "Racista",
        "Ramera",
        "Semen",
        "Sexo",
        "Sexo oral",
        "Soplagaitas",
        "Soplapollas",
        "Sádico",
        "Tetas grandes",
        "Travesti",
        "Trio",
        "Tía buena",
        "Verga",
        "Vulva",
        "aborto",
        "agallas",
        "anal",
        "ano",
        "arrebatar",
        "asno",
        "atornillar",
        "bastardo",
        "bestial",
        "bestialidad",
        "bolas",
        "bollok",
        "bolsa de pelota",
        "brida",
        "buceta",
        "cabron",
        "cagadas",
        "cagado",
        "cagando",
        "campana",
        "carajo",
        "chupar la polla",
        "cipa",
        "clítoris",
        "concha",
        "consolador",
        "consoladores",
        "corrida",
        "coño",
        "coños",
        "culo",
        "culos",
        "cunillingus",
        "córneo",
        "de mierda",
        "dique",
        "duche",
        "enojado",
        "escroto",
        "espacio",
        "estúpido",
        "extremo",
        "eyacula",
        "eyaculación",
        "eyaculado",
        "eyacular",
        "fagging",
        "felación",
        "felching",
        "folla",
        "follada",
        "follador de culo",
        "folladores",
        "follar",
        "fudge packer",
        "gallos",
        "grieta",
        "hacerse una paja",
        "hijo de puta",
        "hore",
        "infierno",
        "kock",
        "labios vaginales",
        "los pechos",
        "lujuria",
        "madre folladora",
        "maldita sea",
        "maldito",
        "maldito sea",
        "mamada",
        "mapache",
        "maricones",
        "maricón",
        "martillo",
        "masoquista",
        "masturbarse",
        "mear",
        "mierda",
        "molesto",
        "muncher alfombra",
        "nazi",
        "negro",
        "niggers",
        "orgasimo",
        "orgasmo",
        "orgasmos",
        "orinando",
        "pelusa",
        "pene",
        "perra",
        "perras",
        "perro follador",
        "pinchazo",
        "pinchazos",
        "pisser",
        "polla",
        "porno",
        "pornografía",
        "pube",
        "puta",
        "putas",
        "pájaro carpintero",
        "quejas",
        "recto",
        "retardar",
        "rimming",
        "sangriento",
        "semen",
        "sexo",
        "skank",
        "smegma",
        "sádico",
        "testículo",
        "teta",
        "tetas",
        "tirón",
        "tizón",
        "tonto",
        "vagina",
        "vete a la mierda",
        "viagra",
        "violación",
        "violador",
        "vulva",
        "wang",
        "x clasificado",
        "xxx",
        "zurullo",
    ],
    "eu": english_flagged_words + [],
    "fr": english_flagged_words
    + [
        "baiseurs",
        "baiseur",
        "baiseuse",
        "baiseuses",
        "branlette",
        "branlettes",
        "branleuse",
        "branleuses",
        "cunillingus",
        "cunilingus",
        "enculée",
        "enculées",
        "enculation",
        "enculations",
        "enculement",
        "enculements",
        "fellation",
        "fellations",
        "porno",
        "pornos",
        "pornographie",
        "pornographique",
        "pornographiques",
        "salope",
        "salopes",
        "suceuse",
        "suceuses",
        "xxx",
    ],
    "ha": english_flagged_words
    + [
        "bf",
        "bura",
        "burar",
        "cin gindi",
        "duri",
        "durin",
        "gindi",
        "gindin",
        "guntsu",
        "guntsun",
        "karuwa",
        "karuwai",
        "karuwar",
        "maniyyi",
        "maɗigo",
        "maɗugo",
        "nonuwa",
        "shan gindi",
        "tsuliya",
        "tsuliyariskanci",
        "ɗuwaiwai",
        "ɗuwaiwan",
        "ɗuwawu",
        "ɗuwawun",
    ],
    "hi": english_flagged_words
    + [
        "अंडकोश की थैली",
        "एक्स रेटेड",
        "ओगाज़्म",
        "कामोद्दीपक चित्र",
        "कालीन का चूरा",
        "कून",
        "कॉक",
        "गेंद का थैला",
        "चाकलेट का रंग",
        "चूची",
        "चूतड़",
        "झटका बंद",
        "ठगना पैकर",
        "डिल्डो",
        "नितंब",
        "पिछाड़ी",
        "पीड़न कामुक",
        "पॉर्न",
        "फटना",
        "फूहड़",
        "बट",
        "बहुत मदहोश",
        "बेल अंत",
        "भगवान-शापित",
        "भगशेफ",
        "माँ कमीने",
        "मुखमैथुन",
        "मुर्गा चूसने वाला",
        "रक्तरंजित",
        "लेबिया",
        "वहशी",
        "वहशीता",
        "वैंग",
        "शिश्नमल",
        "संभोग सुख",
        "सह शॉट",
        "सींग का बना हुआ",
        "होर",
        "घपा घप",
        "चुदाई",
        "चुदक्कड़",
    ],
    "id": english_flagged_words
    + [
        "grepe",
        "horni",
        "janda",
        "jembut",
        "jilat memek",
        "jilmek",
        "kontol",
        "masturbasi",
        "memek",
        "peju",
        "pepek",
        "pornografi",
        "sepong",
        "tusbol",
        "tusuk bola",
    ],
    "kn": english_flagged_words
    + [
        "ಗರ್ಭಪಾತ",
        "ಗುದ",
        "ಗುದದ್ವಾರ",
        "ಕತ್ತೆ",
        "ಆಶ್-ಫಕರ್",
        "ಅಸ್ಹೋಲ್",
        "ಅಸೋಲೆಸ್",
        "ಬಾಲ್ಬಾಗ್",
        "ಚೆಂಡುಗಳು",
        "ಬಾಸ್ಟರ್ಡ್",
        "ಬೆಲೆಂಡ್",
        "ಮೃದ್ವಂಗಿ",
        "ಪ್ರಾಣಿಜನ್ಯತೆ",
        "ಬಿಚ್",
        "ಬಿಟ್ಚಿಸ್",
        "ಬೆಚಿಂಗ್",
        "ರಕ್ತಸಿಕ್ತ",
        "ಬ್ಲೋಜಾಬ್",
        "ಬೊಲ್ಲೊಕ್",
        "ಕುರುಚಲು ಗಿಡ",
        "ಬೂಬಿಗಳು",
        "ಸ್ತನಗಳನ್ನು",
        "ಬುಕೆಟಾ",
        "ತಿಕ",
        "ಬಟ್",
        "ಕಾರ್ಪೆಟ್ ಮಂಚರ್",
        "ಚಿಂಕ್",
        "ಸಿಪಾ",
        "ಚಂದ್ರನಾಡಿ",
        "ಕೋಳಿ",
        "ಕೋಳಿ ಸಕ್ಕರ್",
        "ಕಾಕ್ಸ್",
        "ಕೂನ್",
        "ಅಮೇಧ್ಯ",
        "ಕಮ್",
        "ಕಮ್ಶಾಟ್",
        "ಕುನಿಲ್ಲಸ್",
        "ಕಂಟ್",
        "ಡ್ಯಾಮ್",
        "ಡಿಕ್",
        "ದ್ವಿಧ್ರುವಿ",
        "dildos",
        "ಡಿಂಕ್",
        "ನಾಯಿ-ಫಕರ್",
        "ಡಚೆ",
        "ಡೈಕ್",
        "ಹೊರಹೊಮ್ಮಿಸು",
        "ಸ್ಫೂರ್ತಿ",
        "ಎಜಾಕ್ಯುಲೇಟ್ಸ್",
        "ಇಜಲಲೇಟಿಂಗ್",
        "ಉದ್ಗಾರ",
        "ತಮಾಷೆ",
        "ಮಂದಗತಿ",
        "ಮಬ್ಬು",
        "fagots",
        "ಫ್ಯಾನಿ",
        "ಹೊಡೆತ",
        "ಪತನ",
        "ಚಾಚುಪಟ್ಟಿ",
        "ಫಕ್",
        "ನಾಶವಾಗಿದ್ದನು",
        "ಫಕರ್",
        "fuckers",
        "ಫಕಿಂಗ್",
        "ಫಕಿಂಗ್ಸ್",
        "ಇಷ್ಟಪಡುತ್ತಾನೆ",
        "ಮಿಠಾಯಿ ಪ್ಯಾಕರ್",
        "ದೇವರನ್ನು ಹಾನಿಗೊಳಗಾಯಿತು",
        "ಗಾಡ್ಡಮ್",
        "ನರಕ",
        "ಹೋರ್",
        "ಮೊನಚಾದ",
        "ಜರ್ಕ್-ಆಫ್",
        "ಕೋಕ್",
        "ಯೋನಿಯ",
        "ಕಾಮ",
        "ಕಾಮುಕ",
        "ಮಾಸೋಚಿಸ್ಟ್",
        "ಹಸ್ತಮೈಥುನ ಮಾಡು",
        "ತಾಯಿ ಫಕರ್",
        "ನಾಜಿ",
        "ನಿಗರ್",
        "ನಿಗ್ಗರ್ಗಳು",
        "ಒರಾಸಿಮ್",
        "ಪರಾಕಾಷ್ಠೆ",
        "ಪರಾಕಾಷ್ಠೆಗಳನ್ನು",
        "ಪೆಕರ್",
        "ಶಿಶ್ನ",
        "ಮೂತ್ರ ವಿಸರ್ಜಿಸು",
        "ನಿರುತ್ಸಾಹಗೊಂಡಿದೆ",
        "ಪಿಸರ್",
        "ಮೂತ್ರಪಿಂಡಗಳು",
        "pissing",
        "ಪಿಸ್ಸಾಫ್",
        "ಪೂಪ್",
        "ಅಶ್ಲೀಲತೆ",
        "ಅಶ್ಲೀಲ",
        "ಚುಚ್ಚು",
        "ಪ್ರಿಕ್ಸ್",
        "ಪಬ್",
        "ಪುಸಿಗಳು",
        "ಪುಸಿ",
        "ಅತ್ಯಾಚಾರ",
        "ಅತ್ಯಾಚಾರಿ",
        "ಗುದನಾಳದ",
        "ರಿಟಾರ್ಡ್",
        "ಹಚ್ಚುವುದು",
        "ದುಃಖಗಾರ",
        "ತಿರುಗಿಸುವುದು",
        "ಸ್ಕ್ರೋಟಮ್",
        "ವೀರ್ಯ",
        "ಲೈಂಗಿಕತೆ",
        "ಶಾಗ್",
        "ಶಾಗ್ಗಿಂಗ್",
        "ಶೆಮೇಲ್",
        "ಶಿಟ್",
        "ಷೈಟ್",
        "ಶಿಟ್ಸ್",
        "shitted",
        "ಅಲುಗಾಡುವಿಕೆ",
        "ಅಸಹ್ಯ",
        "ಸ್ಕಾಂಕ್",
        "ಸೂಳೆ",
        "ಸ್ಲಟ್ಗಳು",
        "ಸ್ಮೆಗ್ಮಾ",
        "ಕೊಳೆತ",
        "ಸ್ನ್ಯಾಚ್",
        "ಮಗ-ಆಫ್-ಬಿಚ್",
        "spac",
        "ಉಬ್ಬು",
        "ವೃಷಣ",
        "ಟಿಟ್",
        "ಚೇಕಡಿ ಹಕ್ಕಿಗಳು",
        "turd",
        "ಯೋನಿ",
        "ವಯಾಗ್ರ",
        "ವಾಂಗ್",
        "ಮುಷ್ಕರ",
        "x ರೇಟೆಡ್",
        "xxx",
    ],
    "ml": english_flagged_words
    + [
        "ഗർഭഛിദ്രം",
        "വിശപ്പ്",
        "മലദ്വാരം",
        "കഴുത",
        "അസി ഫക്കർ",
        "കഴുതകളെ",
        "ആസ്ഹോൾ",
        "അശ്ളീലങ്ങൾ",
        "ബോൾബാഗ്",
        "പന്തുകൾ",
        "തന്തയില്ലാത്തവൻ",
        "ബെല്ലെൻഡ്",
        "മൃഗീയമായ",
        "മൃഗീയത",
        "ബിച്ച്",
        "ബിച്ചുകൾ",
        "ബിപിഡിംഗ്",
        "രക്തരൂക്ഷിതമായ",
        "ആശ്വാസം",
        "ബലോക്ക്",
        "ബോബ്",
        "പൂക്കൾ",
        "സ്തനങ്ങൾ",
        "ബ്യൂട്ടാ",
        "ബം",
        "മയക്കുമരുന്ന്",
        "പരവതാനി മാൻച്ചർ",
        "ചുംബ്",
        "സിപാ",
        "ക്ലോറിസിസ്",
        "കോക്ക്",
        "കോക്ക് സക്കർ",
        "കോക്സ്",
        "കോൺ",
        "ക്രാപ്പ്",
        "ശുക്ലം",
        "പുരുഷാരം",
        "സി",
        "മുഷിഞ്ഞ",
        "കഷ്ടം",
        "ഡിക്ക്",
        "ഡിൽഡോ",
        "dildos",
        "ഡൈൻ",
        "നായ-ഫക്കർ",
        "ഡച്ച്",
        "ഡൈകെ",
        "ശമിപ്പിക്കുക",
        "മോഷ്ടിച്ചു",
        "വികാരങ്ങൾ",
        "വിരസത",
        "മടി",
        "ക്ഷീണിപ്പിക്കുക",
        "fagot",
        "വഞ്ചന",
        "ഫാനി",
        "വേദന",
        "flange",
        "ഊമ്പി",
        "സംഭോഗം ചെയ്യുക",
        "ഫക്കർ",
        "നർമ്മം",
        "ഫഡ്ജ് പാക്കർ",
        "ദൈവം-കൊള്ളിത",
        "ഗോഡ്ഡം",
        "നരകം",
        "വയ്ക്കുക",
        "വൃത്തികെട്ട",
        "ജെർക് ഓഫ്",
        "കിക്ക്",
        "ലാബിയ",
        "മോഹം",
        "മോഹഭംഗം",
        "മാസോച്ചിസ്റ്റ്",
        "സ്വയംഭോഗം ചെയ്യുക",
        "അമ്മ ഫക്കർ",
        "നാസി",
        "നിഗർ",
        "മയക്കുമരുന്നുകൾ",
        "രതിമൂർച്ഛ",
        "പെക്കർ",
        "ലിംഗം",
        "മൂത്രമൊഴിക്കുക",
        "കുഴഞ്ഞുവീഴുന്നു",
        "പിസ്സർ",
        "പിസ്സകൾ",
        "pissing",
        "പിസ്സോഫ്",
        "poop",
        "അശ്ലീലം",
        "അശ്ലീലത",
        "പ്രാവി",
        "വിസർജ്യങ്ങൾ",
        "പ്യൂബ്",
        "pussies",
        "pussy",
        "ബലാൽസംഗം",
        "ബലാത്സംഗം",
        "മലാശയം",
        "തുടരുക",
        "റിമ്മിംഗ്",
        "സചിസ്റ്റ്",
        "വഞ്ചി",
        "പുല്ല്",
        "ബീജം",
        "ശവം",
        "ഷാഗിംഗ്",
        "അവൾ",
        "ഷീറ്റ്",
        "ഷെയ്റ്റ്",
        "shits",
        "തിന്നിട്ടില്ല",
        "ഷോർട്ട്",
        "ഷൈറ്റി",
        "സ്കാൻ",
        "മന്ദഹസരം",
        "സ്നെഗമാ",
        "പുഞ്ചിരി",
        "പിടിക്കുക",
        "വെറുക്കപ്പെട്ടയാൾ",
        "സ്പെയ്ക്",
        "തുളച്ച്",
        "വൃഷണം",
        "പേ",
        "ടിത്ത്",
        "കുഴപ്പമില്ല",
        "യോനി",
        "വരാഗ്ര",
        "വാൽവ",
        "വാങ്",
        "വാൻ",
        "വേശ്യ",
        "x റേറ്റുചെയ്തു",
        "xxx",
    ],
    "mr": english_flagged_words
    + [
        "गर्भपात",
        "गुदा",
        "गाढव",
        "गांडुळ",
        "asses",
        "asshole",
        "assholes",
        "ballbag",
        "चेंडू",
        "बॅस्टर्ड",
        "बेलेंड",
        "बेस्टियल",
        "प्राण्यांबरोबर",
        "कुत्री",
        "बिट्स",
        "खूनी",
        "blowjob",
        "बोलोक",
        "बोब",
        "स्तन",
        "बसीटा",
        "बम",
        "बट",
        "कार्पेट मुन्चर",
        "चिंक",
        "सिपा",
        "क्लिटोरिस",
        "मुर्ख",
        "मांसाहारी",
        "कॉक्स",
        "कॉनन",
        "बकवास",
        "सह",
        "cumshot",
        "कनिलिंगस",
        "कांट",
        "धिक्कार",
        "डिक",
        "dildo",
        "डिल्डो",
        "डंक",
        "duche",
        "डाईक",
        "उद्गार",
        "उत्साही",
        "ejaculates",
        "उत्सुकता",
        "स्खलन",
        "फॅग",
        "फॅगिंग",
        "फॅगॉट",
        "फॅगॉट्स",
        "फॅनी",
        "फेलिंग",
        "फॅलेटीओ",
        "निकला",
        "fucked",
        "गुप्तचर",
        "fuckers",
        "fucking",
        "fuckings",
        "fucks",
        "फडगे पॅकर",
        "देव-शापित",
        "देव",
        "नरक",
        "होरे",
        "शिंग",
        "झटका बंद",
        "कॉक",
        "लॅबिया",
        "वासना",
        "मासोचिस्ट",
        "हस्तमैथुन करा",
        "आई माकड",
        "नाझी",
        "निगर",
        "निगार",
        "ऑर्गॅसिम",
        "संभोग",
        "orgasms",
        "चापटी",
        "पुरुषाचे जननेंद्रिय",
        "पेशी",
        "pissed",
        "पिसर",
        "pisses",
        "पिसिंग",
        "पिसोफ",
        "घाट",
        "अश्लील",
        "पोर्नोग्राफी",
        "मुरुम",
        "प्रिक्स",
        "प्यूब",
        "pussies",
        "मांजर",
        "बलात्कार",
        "गुदाशय",
        "मंद",
        "rimming",
        "दुःखी",
        "screwing",
        "स्क्रोटम",
        "वीर्य",
        "लिंग",
        "शेग",
        "shagging",
        "शेमले",
        "विचित्र",
        "shite",
        "shits",
        "shitted",
        "shitting",
        "shitty",
        "घाणेरडा",
        "फट",
        "sluts",
        "सुगंध",
        "स्मट",
        "छेडछाड",
        "मुलगा-एक-कुत्री",
        "spac",
        "तिरस्कार",
        "परीक्षक",
        "शीर्षक",
        "टिट",
        "टर्ड",
        "योनी",
        "वियाग्रा",
        "वल्वा",
        "वांग",
        "विंक",
        "वेश्या",
        "एक्स रेट केले",
        "xxx",
    ],
    "pt": english_flagged_words
    + [
        "aborto",
        "amador",
        "anal",
        "aparafusar",
        "aranha",
        "ariano",
        "arrebatar",
        "ass-filho da puta",
        "asses",
        "balalao",
        "bastardo",
        "bate uma",
        "bellend",
        "bestial",
        "bestialidade",
        "bicha",
        "bichano",
        "bichanos",
        "bichas",
        "biscate",
        "bissexual",
        "boceta",
        "bolas",
        "bollok",
        "boob",
        "boquete",
        "bosta",
        "braulio de borracha",
        "buceta",
        "bumbum",
        "bunda",
        "burro",
        "cabrao",
        "cacete",
        "cadela",
        "cadelas",
        "cagando",
        "cagar",
        "calçado",
        "camisinha",
        "caralho",
        "cerveja",
        "chochota",
        "chupar",
        "cipa",
        "clitoris",
        "clitóris",
        "cobiçoso",
        "cocaína",
        "cocô",
        "coito",
        "colhoes",
        "com tesão",
        "comedor de tapetes",
        "comer",
        "cona",
        "consolo",
        "coon",
        "coragem",
        "corno",
        "cu",
        "cunillingus",
        "dar o rabo",
        "desgraçado",
        "dildo",
        "dildos",
        "dink",
        "dog-filho da puta",
        "droga",
        "duche",
        "dum raio",
        "ejacula",
        "ejaculado",
        "ejacular",
        "ejaculação",
        "empacotador de fudge",
        "escroto",
        "esporra",
        "estuprador",
        "estupro",
        "fagging",
        "fanny",
        "fecal",
        "felação",
        "felching",
        "fenda",
        "filho da puta",
        "filhos da puta",
        "foda",
        "foda-se",
        "fode",
        "foder",
        "fodido",
        "frango assado",
        "galo",
        "galos",
        "gozada",
        "gozar",
        "grelho",
        "heroína",
        "homoerótico",
        "homosexual",
        "hore",
        "idiota",
        "idiotas",
        "inferno",
        "kock",
        "lolita",
        "luxúria",
        "lábios",
        "lésbica",
        "maldito",
        "mama",
        "masoquista",
        "masturbar",
        "merda",
        "merdas",
        "mesa",
        "mijando",
        "mijar",
        "nazista",
        "negro",
        "niggers",
        "não me chateies",
        "orgasim",
        "orgasmo",
        "orgasmos",
        "otário",
        "paneleiro",
        "passar um cheque",
        "pau",
        "peidar",
        "peitos",
        "peituda",
        "pica",
        "picadas",
        "pinto",
        "pisser",
        "porcaria",
        "porno",
        "pornografia",
        "pornô",
        "porra",
        "prostituta",
        "pube",
        "punheta",
        "puta",
        "puta que pariu",
        "puta que te pariu",
        "putaria",
        "puto",
        "pênis",
        "queca",
        "retardar",
        "reto",
        "rimming",
        "sacanagem",
        "saco",
        "saco de bola",
        "sangrento",
        "sapatona",
        "sexo",
        "shite",
        "skank",
        "smegma",
        "spac",
        "sujeira",
        "sádico",
        "sêmen",
        "testículo",
        "tetas",
        "titt",
        "torneira",
        "transando",
        "transar",
        "transsexual",
        "trepada",
        "vadia",
        "vadias",
        "vagabunda",
        "vagabundo",
        "vagina",
        "vai tomar no cu",
        "vai-te foder",
        "veado",
        "viagra",
        "vibrador",
        "vulva",
        "wang",
        "x avaliado",
        "xana",
        "xixi",
        "xochota",
        "xxx",
        "ânus",
    ],
    "ta": english_flagged_words
    + [
        "ஓதா",
        "ஒத்தா",
        "புண்டை",
        "ஒம்மாளே",
        "பக்கி",
        "கூமுட்டை",
        "கருமம்",
        "சனியன்",
        "கஸ்மாலம்",
        "சூத்து",
    ],
    "te": english_flagged_words
    + [
        "గర్భస్రావం",
        "అంగ",
        "పాయువు",
        "గాడిద",
        "గాడిద-fucker",
        "asses",
        "assholes",
        "బాల్బ్యాగ్",
        "బంతుల్లో",
        "బాస్టర్డ్",
        "బెల్లెండ్",
        "మృగ",
        "బెస్టియాలిటీ",
        "బిచ్",
        "bitches",
        "బిట్చింగ్",
        "బ్లడీ",
        "blowjob",
        "బోల్లక",
        "బూబ్",
        "వక్షోజాలను",
        "ఛాతీ",
        "buceta",
        "బం",
        "బట్",
        "కార్పెట్ ముంచర్",
        "చింక్",
        "cipa",
        "స్త్రీగుహ్యాంకురము",
        "ఆత్మవిశ్వాసం",
        "కాక్-సక్కర్",
        "కాక్స్",
        "కూన్",
        "చెత్త",
        "కం",
        "cumshot",
        "క్యునిల్లింగస్",
        "కంట్",
        "తిట్టు",
        "డిక్",
        "లైంగిక సంతృప్తి కోసం స్త్రీలు ఉపయోగించే పురుషాంగము వంటి పరికరము",
        "డిల్డోస్",
        "dink",
        "కుక్క-fucker",
        "డూష్",
        "డైక్",
        "స్ఖలించు",
        "ఎజాక్యులేటెడ్",
        "ఎజాక్యులేట్స్",
        "ఎరాక్యులేటింగ్",
        "స్ఖలనం",
        "నవుకరు",
        "ఫాగ్గింగ్",
        "ఫాగాట్",
        "ఫగాట్స్",
        "fanny",
        "ఫెల్చింగ్",
        "కుడుచుట",
        "అచ్చు",
        "ఫక్",
        "ఇబ్బంది పెట్టాడు",
        "fucker",
        "ఫకర్స్",
        "ఫకింగ్",
        "ఫకింగ్స్",
        "ఫక్స్",
        "ఫడ్జ్ ప్యాకర్",
        "దేవతలా మంచిది",
        "గాడ్డామ్",
        "నరకం",
        "హోర్",
        "horny",
        "జెర్క్-ఆఫ్",
        "కాక్",
        "పెదవి",
        "కామం",
        "మనసు పడ్డట్లు చిత్రించారు",
        "masochist",
        "హస్తప్రయోగం",
        "తల్లి ఫెకర్",
        "నాజీ",
        "నిగ్గర్",
        "నిగ్గర్స్",
        "ఆర్గాసిమ్",
        "స్కలనం",
        "orgasms",
        "pecker",
        "పురుషాంగం",
        "విసర్జన",
        "pissed",
        "పిస్సర్",
        "పిస్సీస్",
        "పిస్సింగ్",
        "పిస్సాఫ్",
        "poop",
        "శృంగార",
        "పోర్నో",
        "అశ్లీల",
        "బుడతడు",
        "ప్రిక్స్",
        "ప్యూబ్",
        "pussies",
        "పుస్సీ",
        "రేప్",
        "ఉన్నప్పటికీ బలాత్కారం",
        "పురీషనాళం",
        "రిటార్డ్",
        "రిమ్మింగ్",
        "పీడన కాముకత",
        "screwing",
        "స్క్రోటమ్",
        "వీర్యం",
        "సెక్స్",
        "బొచ్చు",
        "షగ్గింగ్",
        "షీమేల్",
        "ఒంటి",
        "షైట్",
        "షిట్స్",
        "షిట్టెడ్",
        "షిట్టింగ్",
        "shitty",
        "స్కాన్క్",
        "నీతి",
        "స్లట్స్",
        "శిశ్న",
        "స్మట్",
        "స్నాచ్",
        "ఒక బిచ్ కుమారుడు ఆఫ్",
        "spac",
        "స్పంక్",
        "వృషణాలు",
        "తునక",
        "టిట్స్",
        "టిట్",
        "turd",
        "యోని",
        "వయాగ్రా",
        "జననాంగం",
        "వాంగ్",
        "వ్యాంక్",
        "వేశ్య",
        "x రేట్",
        "xxx",
    ],
    "vi": english_flagged_words
    + [
        "cặc",
        "lồn",
        "địt",
        "buồi",
        "đụ",
        "nứng",
        "phò",
        "bú lol",
        "bú lon",
        "bú cac",
        "bú cak",
        "bú cax",
        "bú buoi",
        "bú mút",
        "húp lol",
        "húp lon",
        "húp sò",
        "nung lol",
        "nung lon",
        "nug lon",
        "nung cac",
        "nung buoi",
        "thèm dit",
        "thèm lon",
        "thèm lol",
        "thèm buoi",
        "thèm dit",
        "thèm chich",
        "thèm chịch",
        "thèm cax",
        "thèm cak",
        "móc lol",
        "móc lon",
        "buscu",
        "lol non",
        "bướm non",
        "vú to",
        "vú bự",
        "lon to",
        "phim sex",
        "phim xex",
        "phim xxx",
    ],
    "zh": english_flagged_words
    + [
        "三级片",
        "乳交",
        "卖B",
        "卖比",
        "卖淫",
        "口交",
        "姣西",
        "打炮",
        "打飞机",
        "抽插",
        "招妓",
        "插你",
        "插死你",
        "淫水",
        "肉壁",
        "肉棍子",
        "肉缝",
        "肏",
        "肛交",
    ],
}
