import pandas as pd

# TODO: Complete this dataframe by adding for each
# language the id of the kenlm model, and the langid lib
langs_id = [
    {
        "lang": "Afrikaans",
        "oscar_id": "af",
        "nltk_id": None,
        "kenlm_id": "af",
        "fasttext_id": "af",
    },
    {
        "lang": "Tosk Albanian",
        "oscar_id": "als",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "als",
    },
    {
        "lang": "Amharic",
        "oscar_id": "am",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "am",
    },
    {
        "lang": "Aragonese",
        "oscar_id": "an",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "an",
    },
    {
        "lang": "Arabic",
        "oscar_id": "ar",
        "nltk_id": "arabic",
        "kenlm_id": "ar",
        "fasttext_id": "ar",
    },
    {
        "lang": "Egyptian Arabic",
        "oscar_id": "arz",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "arz",
    },
    {
        "lang": "Asturian",
        "oscar_id": "ast",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "ast",
    },
    {
        "lang": "Assamese",
        "oscar_id": "as",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "as",
    },
    {
        "lang": "Avaric",
        "oscar_id": "av",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "av",
    },
    {
        "lang": "South Azerbaijani",
        "oscar_id": "azb",
        "nltk_id": "azerbaijani",
        "kenlm_id": None,
        "fasttext_id": "azb",
    },
    {
        "lang": "Azerbaijani",
        "oscar_id": "az",
        "nltk_id": "azerbaijani",
        "kenlm_id": "az",
        "fasttext_id": "az",
    },
    {
        "lang": "Bavarian",
        "oscar_id": "bar",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "bar",
    },
    {
        "lang": "Bashkir",
        "oscar_id": "ba",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "ba",
    },
    {
        "lang": "Central Bikol",
        "oscar_id": "bcl",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "bcl",
    },
    {
        "lang": "Belarusian",
        "oscar_id": "be",
        "nltk_id": None,
        "kenlm_id": "be",
        "fasttext_id": "be",
    },
    {
        "lang": "Bulgarian",
        "oscar_id": "bg",
        "nltk_id": None,
        "kenlm_id": "bg",
        "fasttext_id": "bg",
    },
    {
        "lang": "Bihari",
        "oscar_id": "bh",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "bh",
    },
    {
        "lang": "Bengali",
        "oscar_id": "bn",
        "nltk_id": "bengali",
        "kenlm_id": "bn",
        "fasttext_id": "bn",
    },
    {
        "lang": "Tibetan",
        "oscar_id": "bo",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "bo",
    },
    {
        "lang": "Bishnupriya",
        "oscar_id": "bpy",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "bpy",
    },
    {
        "lang": "Breton",
        "oscar_id": "br",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "br",
    },
    {
        "lang": "Bosnian",
        "oscar_id": "bs",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "bs",
    },
    {
        "lang": "Russia Buriat",
        "oscar_id": "bxr",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "bxr",
    },
    {
        "lang": "Catalan",
        "oscar_id": "ca",
        "nltk_id": None,
        "kenlm_id": "ca",
        "fasttext_id": "ca",
    },
    {
        "lang": "Chavacano",
        "oscar_id": "cbk",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "cbk",
    },
    {
        "lang": "Cebuano",
        "oscar_id": "ceb",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "ceb",
    },
    {
        "lang": "Chechen",
        "oscar_id": "ce",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "ce",
    },
    {
        "lang": "Central Kurdish",
        "oscar_id": "ckb",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "ckb",
    },
    {
        "lang": "Czech",
        "oscar_id": "cs",
        "nltk_id": None,
        "kenlm_id": "cs",
        "fasttext_id": "cs",
    },
    {
        "lang": "Chuvash",
        "oscar_id": "cv",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "cv",
    },
    {
        "lang": "Welsh",
        "oscar_id": "cy",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "cy",
    },
    {
        "lang": "Danish",
        "oscar_id": "da",
        "nltk_id": "danish",
        "kenlm_id": "da",
        "fasttext_id": "da",
    },
    {
        "lang": "German",
        "oscar_id": "de",
        "nltk_id": "german",
        "kenlm_id": "de",
        "fasttext_id": "de",
    },
    {
        "lang": "Dimli",
        "oscar_id": "diq",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "diq",
    },
    {
        "lang": "Lower Sorbian",
        "oscar_id": "dsb",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "dsb",
    },
    {
        "lang": "Dhivehi",
        "oscar_id": "dv",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "dv",
    },
    {
        "lang": "Modern Greek",
        "oscar_id": "el",
        "nltk_id": "greek",
        "kenlm_id": "el",
        "fasttext_id": "el",
    },
    {
        "lang": "Emilian-Romagnol",
        "oscar_id": "eml",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "eml",
    },
    {
        "lang": "English",
        "oscar_id": "en",
        "nltk_id": "english",
        "kenlm_id": "en",
        "fasttext_id": "en",
    },
    {
        "lang": "Esperanto",
        "oscar_id": "eo",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "eo",
    },
    {
        "lang": "Spanish",
        "oscar_id": "es",
        "nltk_id": "spanish",
        "kenlm_id": "es",
        "fasttext_id": "es",
    },
    {
        "lang": "Estonian",
        "oscar_id": "et",
        "nltk_id": None,
        "kenlm_id": "et",
        "fasttext_id": "et",
    },
    {
        "lang": "Basque",
        "oscar_id": "eu",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "eu",
    },
    {
        "lang": "Persian",
        "oscar_id": "fa",
        "nltk_id": None,
        "kenlm_id": "fa",
        "fasttext_id": "fa",
    },
    {
        "lang": "Finnish",
        "oscar_id": "fi",
        "nltk_id": "finnish",
        "kenlm_id": "fi",
        "fasttext_id": "fi",
    },
    {
        "lang": "Northern Frisian",
        "oscar_id": "frr",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "frr",
    },
    {
        "lang": "French",
        "oscar_id": "fr",
        "nltk_id": "french",
        "kenlm_id": "fr",
        "fasttext_id": "fr",
    },
    {
        "lang": "Western Frisian",
        "oscar_id": "fy",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "fy",
    },
    {
        "lang": "Irish",
        "oscar_id": "ga",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "ga",
    },
    {
        "lang": "Scottish Gaelic",
        "oscar_id": "gd",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "gd",
    },
    {
        "lang": "Galician",
        "oscar_id": "gl",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "gl",
    },
    {
        "lang": "Guarani",
        "oscar_id": "gn",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "gn",
    },
    {
        "lang": "Goan Konkani",
        "oscar_id": "gom",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "gom",
    },
    {
        "lang": "Gujarati",
        "oscar_id": "gu",
        "nltk_id": None,
        "kenlm_id": "gu",
        "fasttext_id": "gu",
    },
    {
        "lang": "Hebrew",
        "oscar_id": "he",
        "nltk_id": None,
        "kenlm_id": "he",
        "fasttext_id": "he",
    },
    {
        "lang": "Hindi",
        "oscar_id": "hi",
        "nltk_id": None,
        "kenlm_id": "hi",
        "fasttext_id": "hi",
    },
    {
        "lang": "Croatian",
        "oscar_id": "hr",
        "nltk_id": None,
        "kenlm_id": "hr",
        "fasttext_id": "hr",
    },
    {
        "lang": "Upper Sorbian",
        "oscar_id": "hsb",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "hsb",
    },
    {
        "lang": "Haitian",
        "oscar_id": "ht",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "ht",
    },
    {
        "lang": "Hungarian",
        "oscar_id": "hu",
        "nltk_id": "hungarian",
        "kenlm_id": "hu",
        "fasttext_id": "hu",
    },
    {
        "lang": "Armenian",
        "oscar_id": "hy",
        "nltk_id": None,
        "kenlm_id": "hy",
        "fasttext_id": "hy",
    },
    {
        "lang": "Interlingua",
        "oscar_id": "ia",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "ia",
    },
    {
        "lang": "Indonesian",
        "oscar_id": "id",
        "nltk_id": "indonesian",
        "kenlm_id": "id",
        "fasttext_id": "id",
    },
    {
        "lang": "Interlingue",
        "oscar_id": "ie",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "ie",
    },
    {
        "lang": "Iloko",
        "oscar_id": "ilo",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "ilo",
    },
    {
        "lang": "Ido",
        "oscar_id": "io",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "io",
    },
    {
        "lang": "Icelandic",
        "oscar_id": "is",
        "nltk_id": None,
        "kenlm_id": "is",
        "fasttext_id": "is",
    },
    {
        "lang": "Italian",
        "oscar_id": "it",
        "nltk_id": "italian",
        "kenlm_id": "it",
        "fasttext_id": "it",
    },
    {
        "lang": "Japanese",
        "oscar_id": "ja",
        "nltk_id": None,
        "kenlm_id": "ja",
        "fasttext_id": "ja",
    },
    {
        "lang": "Lojban",
        "oscar_id": "jbo",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "jbo",
    },
    {
        "lang": "Javanese",
        "oscar_id": "jv",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "jv",
    },
    {
        "lang": "Georgian",
        "oscar_id": "ka",
        "nltk_id": None,
        "kenlm_id": "ka",
        "fasttext_id": "ka",
    },
    {
        "lang": "Kazakh",
        "oscar_id": "kk",
        "nltk_id": "kazakh",
        "kenlm_id": "kk",
        "fasttext_id": "kk",
    },
    {
        "lang": "Central Khmer",
        "oscar_id": "km",
        "nltk_id": None,
        "kenlm_id": "km",
        "fasttext_id": "km",
    },
    {
        "lang": "Kannada",
        "oscar_id": "kn",
        "nltk_id": None,
        "kenlm_id": "kn",
        "fasttext_id": "kn",
    },
    {
        "lang": "Korean",
        "oscar_id": "ko",
        "nltk_id": None,
        "kenlm_id": "ko",
        "fasttext_id": "ko",
    },
    {
        "lang": "Karachay-Balkar",
        "oscar_id": "krc",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "krc",
    },
    {
        "lang": "Kurdish",
        "oscar_id": "ku",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "ku",
    },
    {
        "lang": "Komi",
        "oscar_id": "kv",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "kv",
    },
    {
        "lang": "Cornish",
        "oscar_id": "kw",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "kw",
    },
    {
        "lang": "Kirghiz",
        "oscar_id": "ky",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "ky",
    },
    {
        "lang": "Latin",
        "oscar_id": "la",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "la",
    },
    {
        "lang": "Luxembourgish",
        "oscar_id": "lb",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "lb",
    },
    {
        "lang": "Lezghian",
        "oscar_id": "lez",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "lez",
    },
    {
        "lang": "Limburgan",
        "oscar_id": "li",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "li",
    },
    {
        "lang": "Lombard",
        "oscar_id": "lmo",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "lmo",
    },
    {
        "lang": "Lao",
        "oscar_id": "lo",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "lo",
    },
    {
        "lang": "Northern Luri",
        "oscar_id": "lrc",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "lrc",
    },
    {
        "lang": "Lithuanian",
        "oscar_id": "lt",
        "nltk_id": None,
        "kenlm_id": "lt",
        "fasttext_id": "lt",
    },
    {
        "lang": "Latvian",
        "oscar_id": "lv",
        "nltk_id": None,
        "kenlm_id": "lv",
        "fasttext_id": "lv",
    },
    {
        "lang": "Maithili",
        "oscar_id": "mai",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "mai",
    },
    {
        "lang": "Malagasy",
        "oscar_id": "mg",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "mg",
    },
    {
        "lang": "Eastern Mari",
        "oscar_id": "mhr",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "mhr",
    },
    {
        "lang": "Minangkabau",
        "oscar_id": "min",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "min",
    },
    {
        "lang": "Macedonian",
        "oscar_id": "mk",
        "nltk_id": None,
        "kenlm_id": "mk",
        "fasttext_id": "mk",
    },
    {
        "lang": "Malayalam",
        "oscar_id": "ml",
        "nltk_id": None,
        "kenlm_id": "ml",
        "fasttext_id": "ml",
    },
    {
        "lang": "Mongolian",
        "oscar_id": "mn",
        "nltk_id": None,
        "kenlm_id": "mn",
        "fasttext_id": "mn",
    },
    {
        "lang": "Western Mari",
        "oscar_id": "mrj",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "mrj",
    },
    {
        "lang": "Marathi",
        "oscar_id": "mr",
        "nltk_id": None,
        "kenlm_id": "mr",
        "fasttext_id": "mr",
    },
    {
        "lang": "Malay",
        "oscar_id": "ms",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "ms",
    },
    {
        "lang": "Maltese",
        "oscar_id": "mt",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "mt",
    },
    {
        "lang": "Mirandese",
        "oscar_id": "mwl",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "mwl",
    },
    {
        "lang": "Burmese",
        "oscar_id": "my",
        "nltk_id": None,
        "kenlm_id": "my",
        "fasttext_id": "my",
    },
    {
        "lang": "Erzya",
        "oscar_id": "myv",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "myv",
    },
    {
        "lang": "Mazanderani",
        "oscar_id": "mzn",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "mzn",
    },
    {
        "lang": "Nahuatl",
        "oscar_id": "nah",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "nah",
    },
    {
        "lang": "Neapolitan",
        "oscar_id": "nap",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "nap",
    },
    {
        "lang": "Low German",
        "oscar_id": "nds",
        "nltk_id": "german",
        "kenlm_id": None,
        "fasttext_id": "nds",
    },
    {
        "lang": "Nepali",
        "oscar_id": "ne",
        "nltk_id": "nepali",
        "kenlm_id": "ne",
        "fasttext_id": "ne",
    },
    {
        "lang": "Newari",
        "oscar_id": "new",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "new",
    },
    {
        "lang": "Dutch",
        "oscar_id": "nl",
        "nltk_id": "dutch",
        "kenlm_id": "nl",
        "fasttext_id": "nl",
    },
    {
        "lang": "Norwegian Nynorsk",
        "oscar_id": "nn",
        "nltk_id": "norwegian",
        "kenlm_id": None,
        "fasttext_id": "nn",
    },
    {
        "lang": "Norwegian",
        "oscar_id": "no",
        "nltk_id": "norwegian",
        "kenlm_id": "no",
        "fasttext_id": "no",
    },
    {
        "lang": "Occitan",
        "oscar_id": "oc",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "oc",
    },
    {
        "lang": "Oriya",
        "oscar_id": "or",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "or",
    },
    {
        "lang": "Ossetian",
        "oscar_id": "os",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "os",
    },
    {
        "lang": "Pampanga",
        "oscar_id": "pam",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "pam",
    },
    {
        "lang": "Panjabi",
        "oscar_id": "pa",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "pa",
    },
    {
        "lang": "Polish",
        "oscar_id": "pl",
        "nltk_id": None,
        "kenlm_id": "pl",
        "fasttext_id": "pl",
    },
    {
        "lang": "Piemontese",
        "oscar_id": "pms",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "pms",
    },
    {
        "lang": "Western Panjabi",
        "oscar_id": "pnb",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "pnb",
    },
    {
        "lang": "Pushto",
        "oscar_id": "ps",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "ps",
    },
    {
        "lang": "Portuguese",
        "oscar_id": "pt",
        "nltk_id": "portuguese",
        "kenlm_id": "pt",
        "fasttext_id": "pt",
    },
    {
        "lang": "Quechua",
        "oscar_id": "qu",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "qu",
    },
    {
        "lang": "Romansh",
        "oscar_id": "rm",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "rm",
    },
    {
        "lang": "Romanian",
        "oscar_id": "ro",
        "nltk_id": "romanian",
        "kenlm_id": "ro",
        "fasttext_id": "ro",
    },
    {
        "lang": "Russian",
        "oscar_id": "ru",
        "nltk_id": "russian",
        "kenlm_id": "ru",
        "fasttext_id": "ru",
    },
    {
        "lang": "Yakut",
        "oscar_id": "sah",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "sah",
    },
    {
        "lang": "Sanskrit",
        "oscar_id": "sa",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "sa",
    },
    {
        "lang": "Sicilian",
        "oscar_id": "scn",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "scn",
    },
    {
        "lang": "Sindhi",
        "oscar_id": "sd",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "sd",
    },
    {
        "lang": "Serbo-Croatian",
        "oscar_id": "sh",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "sh",
    },
    {
        "lang": "Sinhala",
        "oscar_id": "si",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "si",
    },
    {
        "lang": "Slovak",
        "oscar_id": "sk",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "sk",
    },
    {
        "lang": "Slovenian",
        "oscar_id": "sl",
        "nltk_id": "slovene",
        "kenlm_id": None,
        "fasttext_id": "sl",
    },
    {
        "lang": "Somali",
        "oscar_id": "so",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "so",
    },
    {
        "lang": "Albanian",
        "oscar_id": "sq",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "sq",
    },
    {
        "lang": "Serbian",
        "oscar_id": "sr",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "sr",
    },
    {
        "lang": "Sundanese",
        "oscar_id": "su",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "su",
    },
    {
        "lang": "Swedish",
        "oscar_id": "sv",
        "nltk_id": "swedish",
        "kenlm_id": None,
        "fasttext_id": "sv",
    },
    {
        "lang": "Swahili",
        "oscar_id": "sw",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "sw",
    },
    {
        "lang": "Tamil",
        "oscar_id": "ta",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "ta",
    },
    {
        "lang": "Telugu",
        "oscar_id": "te",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "te",
    },
    {
        "lang": "Tajik",
        "oscar_id": "tg",
        "nltk_id": "tajik",
        "kenlm_id": None,
        "fasttext_id": "tg",
    },
    {
        "lang": "Thai",
        "oscar_id": "th",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "th",
    },
    {
        "lang": "Turkmen",
        "oscar_id": "tk",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "tk",
    },
    {
        "lang": "Tagalog",
        "oscar_id": "tl",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "tl",
    },
    {
        "lang": "Turkish",
        "oscar_id": "tr",
        "nltk_id": "turkish",
        "kenlm_id": "tr",
        "fasttext_id": "tr",
    },
    {
        "lang": "Tatar",
        "oscar_id": "tt",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "tt",
    },
    {
        "lang": "Tuvinian",
        "oscar_id": "tyv",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "tyv",
    },
    {
        "lang": "Uighur",
        "oscar_id": "ug",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "ug",
    },
    {
        "lang": "Ukrainian",
        "oscar_id": "uk",
        "nltk_id": None,
        "kenlm_id": "uk",
        "fasttext_id": "uk",
    },
    {
        "lang": "Urdu",
        "oscar_id": "ur",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "ur",
    },
    {
        "lang": "Uzbek",
        "oscar_id": "uz",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "uz",
    },
    {
        "lang": "Venetian",
        "oscar_id": "vec",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "vec",
    },
    {
        "lang": "Vietnamese",
        "oscar_id": "vi",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "vi",
    },
    {
        "lang": "Volapük",
        "oscar_id": "vo",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "vo",
    },
    {
        "lang": "Waray",
        "oscar_id": "war",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "war",
    },
    {
        "lang": "Walloon",
        "oscar_id": "wa",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "wa",
    },
    {
        "lang": "Wu Chinese",
        "oscar_id": "wuu",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "wuu",
    },
    {
        "lang": "Kalmyk",
        "oscar_id": "xal",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "xal",
    },
    {
        "lang": "Mingrelian",
        "oscar_id": "xmf",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "xmf",
    },
    {
        "lang": "Yiddish",
        "oscar_id": "yi",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "yi",
    },
    {
        "lang": "Yoruba",
        "oscar_id": "yo",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "yo",
    },
    {
        "lang": "Yue Chinese",
        "oscar_id": "yue",
        "nltk_id": None,
        "kenlm_id": None,
        "fasttext_id": "yue",
    },
    {
        "lang": "Chinese",
        "oscar_id": "zh",
        "nltk_id": None,
        "kenlm_id": "zh",
        "fasttext_id": "zh",
    },
]
langs_id = pd.DataFrame(langs_id)
