dic_langs = {
    "af": "Afrikaans",
    "als": "Tosk Albanian",
    "am": "Amharic",
    "an": "Aragonese",
    "ar": "Arabic",
    "arz": "Egyptian Arabic",
    "ast": "Asturian",
    "as": "Assamese",
    "av": "Avaric",
    "azb": "South Azerbaijani",
    "az": "Azerbaijani",
    "bar": "Bavarian",
    "ba": "Bashkir",
    "bcl": "Central Bikol",
    "be": "Belarusian",
    "bg": "Bulgarian",
    "bh": "Bihari",
    "bn": "Bengali",
    "bo": "Tibetan",
    "bpy": "Bishnupriya",
    "br": "Breton",
    "bs": "Bosnian",
    "bxr": "Russia Buriat",
    "ca": "Catalan",
    "cbk": "Chavacano",
    "ceb": "Cebuano",
    "ce": "Chechen",
    "ckb": "Central Kurdish",
    "cs": "Czech",
    "cv": "Chuvash",
    "cy": "Welsh",
    "da": "Danish",
    "de": "German",
    "diq": "Dimli",
    "dsb": "Lower Sorbian",
    "dv": "Dhivehi",
    "el": "Modern Greek",
    "eml": "Emilian-Romagnol",
    "en": "English",
    "eo": "Esperanto",
    "es": "Spanish",
    "et": "Estonian",
    "eu": "Basque",
    "fa": "Persian",
    "fi": "Finnish",
    "frr": "Northern Frisian",
    "fr": "French",
    "fy": "Western Frisian",
    "ga": "Irish",
    "gd": "Scottish Gaelic",
    "gl": "Galician",
    "gn": "Guarani",
    "gom": "Goan Konkani",
    "gu": "Gujarati",
    "he": "Hebrew",
    "hi": "Hindi",
    "hr": "Croatian",
    "hsb": "Upper Sorbian",
    "ht": "Haitian",
    "hu": "Hungarian",
    "hy": "Armenian",
    "ia": "Interlingua",
    "id": "Indonesian",
    "ie": "Interlingue",
    "ilo": "Iloko",
    "io": "Ido",
    "is": "Icelandic",
    "it": "Italian",
    "ja": "Japanese",
    "jbo": "Lojban",
    "jv": "Javanese",
    "ka": "Georgian",
    "kk": "Kazakh",
    "km": "Central Khmer",
    "kn": "Kannada",
    "ko": "Korean",
    "krc": "Karachay-Balkar",
    "ku": "Kurdish",
    "kv": "Komi",
    "kw": "Cornish",
    "ky": "Kirghiz",
    "la": "Latin",
    "lb": "Luxembourgish",
    "lez": "Lezghian",
    "li": "Limburgan",
    "lmo": "Lombard",
    "lo": "Lao",
    "lrc": "Northern Luri",
    "lt": "Lithuanian",
    "lv": "Latvian",
    "mai": "Maithili",
    "mg": "Malagasy",
    "mhr": "Eastern Mari",
    "min": "Minangkabau",
    "mk": "Macedonian",
    "ml": "Malayalam",
    "mn": "Mongolian",
    "mrj": "Western Mari",
    "mr": "Marathi",
    "ms": "Malay",
    "mt": "Maltese",
    "mwl": "Mirandese",
    "my": "Burmese",
    "myv": "Erzya",
    "mzn": "Mazanderani",
    "nah": "Nahuatl",  # languages
    "nap": "Neapolitan",
    "nds": "Low German",
    "ne": "Nepali",
    "new": "Newari",
    "nl": "Dutch",
    "nn": "Norwegian Nynorsk",
    "no": "Norwegian",
    "oc": "Occitan",
    "or": "Oriya",
    "os": "Ossetian",
    "pam": "Pampanga",
    "pa": "Panjabi",
    "pl": "Polish",
    "pms": "Piemontese",
    "pnb": "Western Panjabi",
    "ps": "Pushto",
    "pt": "Portuguese",
    "qu": "Quechua",
    "rm": "Romansh",
    "ro": "Romanian",
    "ru": "Russian",
    "sah": "Yakut",
    "sa": "Sanskrit",
    "scn": "Sicilian",
    "sd": "Sindhi",
    "sh": "Serbo-Croatian",
    "si": "Sinhala",
    "sk": "Slovak",
    "sl": "Slovenian",
    "so": "Somali",
    "sq": "Albanian",
    "sr": "Serbian",
    "su": "Sundanese",
    "sv": "Swedish",
    "sw": "Swahili",
    "ta": "Tamil",
    "te": "Telugu",
    "tg": "Tajik",
    "th": "Thai",
    "tk": "Turkmen",
    "tl": "Tagalog",
    "tr": "Turkish",
    "tt": "Tatar",
    "tyv": "Tuvinian",
    "ug": "Uighur",
    "uk": "Ukrainian",
    "ur": "Urdu",
    "uz": "Uzbek",
    "vec": "Venetian",
    "vi": "Vietnamese",
    "vo": "Volapük",
    "war": "Waray",
    "wa": "Walloon",
    "wuu": "Wu Chinese",
    "xal": "Kalmyk",
    "xmf": "Mingrelian",
    "yi": "Yiddish",
    "yo": "Yoruba",
    "yue": "Yue Chinese",
    "zh": "Chinese",
}

